import { Router } from "express";
import { z } from "zod";
import { authenticate } from "../middleware/auth.js";
import { Group, Topic, User } from "../models/index.js";
import { fail, ok } from "../utils/http.js";

const router = Router();
router.use(authenticate);
const id = z.string().regex(/^[a-f\d]{24}$/i, "Invalid id");
const output = (group: any) => ({ ...group, id: String(group._id), _id: undefined });
const canManage = (group: any, userId: string) => group.creatorIds.some((v: any) => String(v) === userId) || group.leaderIds.some((v: any) => String(v) === userId);
const isCreator = (group: any, userId: string) => group.creatorIds.some((v: any) => String(v) === userId);
async function getGroup(groupId: string) { return Group.findOne({ _id: groupId, deletedAt: null }); }
function member(group: any, userId: string) { return group.memberIds.some((v: any) => String(v) === userId); }
function denied(response: any) { return fail(response, 403, "GROUP_ACCESS_DENIED", "You are not a member of this group"); }

router.get("/", async (request, response, next) => { try { const groups = await Group.find({ memberIds: request.user!.id, deletedAt: null }).sort({ name: 1 }).lean(); return ok(response, { groups: groups.map(output) }); } catch (e) { next(e); } });
router.post("/", async (request, response, next) => { try { const input = z.object({ name: z.string().min(1).max(120), description: z.string().max(1000).default("") }).parse(request.body); const userId = request.user!.id; const group = await Group.create({ ...input, memberIds: [userId], leaderIds: [userId], creatorIds: [userId] }); return ok(response, output(group), 201); } catch (e) { next(e); } });
router.get("/:id", async (request, response, next) => { try { const group = await getGroup(id.parse(request.params.id)); if (!group) return fail(response, 404, "GROUP_NOT_FOUND", "Group not found"); if (request.user!.role !== "SUPERADMIN" && !member(group, request.user!.id)) return denied(response); const [members, topics] = await Promise.all([User.find({ _id: { $in: group.memberIds }, deletedAt: null }).select("name email").sort({ name: 1 }).lean(), Topic.find({ groupId: group._id }).sort({ name: 1 }).lean()]); return ok(response, { group: output(group), members, topics }); } catch (e) { next(e); } });
router.post("/:id/members", async (request, response, next) => { try { const group = await getGroup(id.parse(request.params.id)); if (!group) return fail(response, 404, "GROUP_NOT_FOUND", "Group not found"); if (request.user!.role !== "SUPERADMIN" && !canManage(group, request.user!.id)) return denied(response); const userId = id.parse(z.object({ userId: id }).parse(request.body).userId); const user = await User.findOne({ _id: userId, isActive: true, deletedAt: null }); if (!user) return fail(response, 404, "USER_NOT_FOUND", "User not found"); await Group.updateOne({ _id: group._id }, { $addToSet: { memberIds: user._id } }); return ok(response, { added: true }); } catch (e) { next(e); } });
router.delete("/:id/members/:userId", async (request, response, next) => { try { const group = await getGroup(id.parse(request.params.id)); if (!group) return fail(response, 404, "GROUP_NOT_FOUND", "Group not found"); if (request.user!.role !== "SUPERADMIN" && !canManage(group, request.user!.id)) return denied(response); const userId = id.parse(request.params.userId); if (group.memberIds.length <= 1) return fail(response, 400, "LAST_MEMBER", "A group must have at least one member"); await Group.updateOne({ _id: group._id }, { $pull: { memberIds: userId, leaderIds: userId, creatorIds: userId } }); return ok(response, { removed: true }); } catch (e) { next(e); } });
router.patch("/:id/roles/:userId", async (request, response, next) => { try { const group = await getGroup(id.parse(request.params.id)); if (!group) return fail(response, 404, "GROUP_NOT_FOUND", "Group not found"); if (request.user!.role !== "SUPERADMIN" && !isCreator(group, request.user!.id)) return denied(response); const userId = id.parse(request.params.userId); if (!member(group, userId)) return fail(response, 400, "NOT_A_MEMBER", "User must be a group member first"); const input = z.object({ creator: z.boolean().optional(), leader: z.boolean().optional() }).parse(request.body); const update: any = {}; for (const [role, enabled] of Object.entries(input)) if (enabled !== undefined) update[enabled ? "$addToSet" : "$pull"] = { ...(update[enabled ? "$addToSet" : "$pull"] || {}), [`${role}Ids`]: userId }; await Group.updateOne({ _id: group._id }, update); return ok(response, { updated: true }); } catch (e) { next(e); } });
router.post("/:id/topics", async (request, response, next) => { try { const group = await getGroup(id.parse(request.params.id)); if (!group) return fail(response, 404, "GROUP_NOT_FOUND", "Group not found"); if (request.user!.role !== "SUPERADMIN" && !canManage(group, request.user!.id)) return denied(response); const input = z.object({ name: z.string().min(1).max(120), description: z.string().max(500).default("") }).parse(request.body); const topic = await Topic.create({ ...input, groupId: group._id }); return ok(response, topic, 201); } catch (e) { next(e); } });
router.patch("/:id/topics/:topicId", async (request, response, next) => { try { const group = await getGroup(id.parse(request.params.id)); if (!group) return fail(response, 404, "GROUP_NOT_FOUND", "Group not found"); if (request.user!.role !== "SUPERADMIN" && !canManage(group, request.user!.id)) return denied(response); const input = z.object({ name: z.string().min(1).max(120).optional(), description: z.string().max(500).optional(), archived: z.boolean().optional() }).parse(request.body); const changes: any = { ...input }; if (input.archived !== undefined) { changes.archivedAt = input.archived ? new Date() : null; delete changes.archived; } const topic = await Topic.findOneAndUpdate({ _id: id.parse(request.params.topicId), groupId: group._id }, changes, { new: true }); return topic ? ok(response, topic) : fail(response, 404, "TOPIC_NOT_FOUND", "Topic not found"); } catch (e) { next(e); } });
export { router as groupsRouter };
