import { Router } from "express";
import { z } from "zod";
import { authenticate, requirePermission } from "../middleware/auth.js";
import { ActivityLog, Comment, Counter, Group, Notification, Ticket, TicketLink, Topic, User } from "../models/index.js";
import { fail, ok } from "../utils/http.js";

const router = Router(); router.use(authenticate);
router.use(async (request, response, next) => {
  if (request.method === "PATCH" && (Object.prototype.hasOwnProperty.call(request.body, "assigneeId") || Object.prototype.hasOwnProperty.call(request.body, "assigneeIds")) && request.user?.role !== "SUPERADMIN" && !request.user?.permissions.includes("tickets.assign")) return fail(response, 403, "PERMISSION_DENIED", "Assigning tickets requires tickets.assign");
  return next();
});
const statuses = ["OPEN", "IN_PROGRESS", "IN_REVIEW", "BLOCKED", "COMPLETED", "CLOSED"] as const;
const priorities = ["NO_PRIORITY", "LOW", "MEDIUM", "HIGH", "URGENT"] as const;
const ticketInput = z.object({ title: z.string().min(1).max(200), description: z.string().max(50000).default(""), priority: z.enum(priorities).default("MEDIUM"), assigneeId: z.string().nullable().optional(), assigneeIds: z.array(z.string()).max(50).default([]), dueDate: z.coerce.date().nullable().optional(), groupId: z.string().nullable().optional(), topicIds: z.array(z.string()).max(50).default([]) });
const toView = (ticket: any) => ({ ...ticket, id: String(ticket._id), _id: undefined });
const requireTicketUpdateAccess = (request: any, response: any, next: any) => {
  if (request.user?.role === "SUPERADMIN") return next();
  const fields = Object.keys(request.body || {});
  if (fields.length > 0 && fields.every((field) => field === "assigneeId" || field === "assigneeIds") && request.user?.permissions.includes("tickets.assign")) return next();
  return fail(response, 403, "PERMISSION_DENIED", "Only SuperAdmin can edit ticket details; tickets.assign is required to assign tickets");
};
async function nextTicketNumber() { const counter = await Counter.findOneAndUpdate({ _id: "tickets" }, { $inc: { value: 1 } }, { upsert: true, new: true }); return `TKT-${counter!.value}`; }
async function activity(ticketId: unknown, actorId: string, type: string, metadata: Record<string, unknown> = {}) { await ActivityLog.create({ ticketId, actorId, type, metadata }); }
async function accessibleGroup(groupId: unknown, userId: string, role: string) { if (!groupId) return role === "SUPERADMIN"; const group = await Group.findOne({ _id: groupId, deletedAt: null }).lean(); return !!group && (role === "SUPERADMIN" || group.memberIds.some((id: any) => String(id) === userId)); }
async function validateGroupTopics(groupId: string | null | undefined, topicIds: string[], userId: string, role: string) { if (!groupId) return topicIds.length === 0 && role === "SUPERADMIN"; if (!(await accessibleGroup(groupId, userId, role))) return false; return (await Topic.countDocuments({ _id: { $in: topicIds }, groupId, archivedAt: null })) === new Set(topicIds).size; }
const denied = (response: any) => fail(response, 403, "GROUP_ACCESS_DENIED", "You are not a member of this group");

router.get("/", requirePermission("tickets.view"), async (request, response, next) => { try { const q = z.object({ search: z.string().max(100).optional(), groupId: z.string().optional(), status: z.enum(statuses).optional(), priority: z.enum(priorities).optional(), assigneeId: z.string().optional(), mine: z.coerce.boolean().optional(), page: z.coerce.number().int().positive().default(1), limit: z.coerce.number().int().min(1).max(50).default(20) }).parse(request.query); const filter: any = { deletedAt: null, $and: [] }; if (request.user!.role !== "SUPERADMIN") { const groups = await Group.find({ memberIds: request.user!.id, deletedAt: null }).select("_id").lean(); filter.groupId = q.groupId || { $in: groups.map(g => g._id) }; } else if (q.groupId) filter.groupId = q.groupId; if (q.search) filter.$and.push({ $or: [{ ticketNumber: new RegExp(q.search, "i") }, { title: new RegExp(q.search, "i") }, { description: new RegExp(q.search, "i") }] }); if (q.status) filter.status = q.status; if (q.priority) filter.priority = q.priority; if (q.assigneeId) filter.$and.push({ $or: [{ assigneeId: q.assigneeId }, { assigneeIds: q.assigneeId }] }); if (q.mine) filter.$and.push({ $or: [{ assigneeId: request.user!.id }, { assigneeIds: request.user!.id }] }); const [tickets, total] = await Promise.all([Ticket.find(filter).sort({ updatedAt: -1 }).skip((q.page - 1) * q.limit).limit(q.limit).populate("assigneeId assigneeIds topicIds groupId", "name email").lean(), Ticket.countDocuments(filter)]); return ok(response, { tickets: tickets.map(toView), page: q.page, limit: q.limit, total, pages: Math.ceil(total / q.limit) }); } catch (e) { next(e); } });
router.post("/", requirePermission("tickets.create"), async (request, response, next) => { try { const input = ticketInput.parse(request.body); if (!(await validateGroupTopics(input.groupId, input.topicIds, request.user!.id, request.user!.role))) return fail(response, 403, "GROUP_ACCESS_DENIED", "Choose a group you belong to and its topics"); const assigneeIds = [...new Set([...(input.assigneeIds || []), input.assigneeId].filter(Boolean) as string[])]; if (assigneeIds.length && request.user!.role !== "SUPERADMIN" && !request.user!.permissions.includes("tickets.assign")) return fail(response, 403, "PERMISSION_DENIED", "Assigning tickets requires tickets.assign"); const ticket = await Ticket.create({ ...input, assigneeId: assigneeIds[0] || null, assigneeIds, ticketNumber: await nextTicketNumber(), createdById: request.user!.id, updatedById: request.user!.id }); await activity(ticket._id, request.user!.id, "CREATED", { assigneeIds }); if (assigneeIds.length) await Notification.insertMany(assigneeIds.filter(id => id !== request.user!.id).map(userId => ({ userId, ticketId: ticket._id, type: "TICKET_ASSIGNED", message: `You were assigned ${ticket.ticketNumber}` }))); return ok(response, toView(ticket), 201); } catch (e) { next(e); } });
router.get("/:id", requirePermission("tickets.view"), async (request, response, next) => { try { const ticket = await Ticket.findOne({ _id: request.params.id, deletedAt: null }).populate("assigneeId assigneeIds createdById updatedById topicIds groupId", "name email").lean(); if (!ticket) return fail(response, 404, "TICKET_NOT_FOUND", "Ticket not found"); if (!(await accessibleGroup((ticket as any).groupId?._id || (ticket as any).groupId, request.user!.id, request.user!.role))) return denied(response); const [comments, links, activities] = await Promise.all([Comment.find({ ticketId: ticket._id, deletedAt: null }).populate("authorId", "name email").sort({ createdAt: 1 }).lean(), TicketLink.find({ ticketId: ticket._id }).sort({ createdAt: -1 }).lean(), ActivityLog.find({ ticketId: ticket._id }).populate("actorId", "name email").sort({ createdAt: -1 }).lean()]); return ok(response, { ticket: toView(ticket), comments, links, activities }); } catch (e) { next(e); } });
router.patch("/:id", requireTicketUpdateAccess, async (request, response, next) => { try { const input = ticketInput.partial().extend({ status: z.enum(statuses).optional() }).parse(request.body); const ticket = await Ticket.findOne({ _id: request.params.id, deletedAt: null }); if (!ticket) return fail(response, 404, "TICKET_NOT_FOUND", "Ticket not found"); if (!(await accessibleGroup(ticket.groupId, request.user!.id, request.user!.role))) return denied(response); if (input.groupId !== undefined && !(await validateGroupTopics(input.groupId, input.topicIds || [], request.user!.id, request.user!.role))) return denied(response); if (input.topicIds !== undefined && !(await validateGroupTopics(String(ticket.groupId || input.groupId || ""), input.topicIds, request.user!.id, request.user!.role))) return fail(response, 422, "INVALID_TOPICS", "Topics must belong to the ticket group"); for (const [key, value] of Object.entries(input)) { if (value !== undefined) { const old = (ticket as any)[key]; (ticket as any)[key] = value; if (old?.toString() !== value?.toString()) await activity(ticket._id, request.user!.id, `${key.toUpperCase()}_CHANGED`, { from: old, to: value }); } } ticket.updatedById = request.user!.id as any; if (input.status === "COMPLETED" || input.status === "CLOSED") ticket.completedAt = ticket.completedAt || new Date(); await ticket.save(); return ok(response, toView(ticket)); } catch (e) { next(e); } });
router.delete("/:id", requirePermission("tickets.delete"), async (request, response, next) => { try { const existing = await Ticket.findOne({ _id: request.params.id, deletedAt: null }); if (!existing) return fail(response, 404, "TICKET_NOT_FOUND", "Ticket not found"); if (!(await accessibleGroup(existing.groupId, request.user!.id, request.user!.role))) return denied(response); const ticket = await Ticket.findOneAndUpdate({ _id: existing._id }, { deletedAt: new Date(), updatedById: request.user!.id }, { new: true }); await activity(ticket!._id, request.user!.id, "DELETED"); return ok(response, null); } catch (e) { next(e); } });

router.post("/:id/comments", requirePermission("comments.create"), async (request, response, next) => { try { const body = z.object({ body: z.string().min(1).max(10000) }).parse(request.body).body; const ticket = await Ticket.findOne({ _id: request.params.id, deletedAt: null }); if (!ticket) return fail(response, 404, "TICKET_NOT_FOUND", "Ticket not found"); const comment = await Comment.create({ ticketId: ticket._id, authorId: request.user!.id, body }); await activity(ticket._id, request.user!.id, "COMMENT_ADDED"); const assigneeIds = [...new Set([String(ticket.assigneeId || ""), ...(ticket.assigneeIds || []).map(String)].filter(id => id && id !== request.user!.id))]; if (assigneeIds.length) await Notification.insertMany(assigneeIds.map(userId => ({ userId, ticketId: ticket._id, type: "TICKET_COMMENTED", message: `${ticket.ticketNumber} received a comment` }))).catch(() => undefined); return ok(response, comment, 201); } catch (e) { next(e); } });
router.patch("/:id/comments/:commentId", requirePermission("comments.edit"), async (request, response, next) => { try { const body = z.object({ body: z.string().min(1).max(10000) }).parse(request.body).body; const filter: any = { _id: request.params.commentId, ticketId: request.params.id, deletedAt: null }; if (request.user!.role !== "SUPERADMIN") filter.authorId = request.user!.id; const comment = await Comment.findOneAndUpdate(filter, { body }, { new: true }); return comment ? ok(response, comment) : fail(response, 404, "COMMENT_NOT_FOUND", "Comment not found"); } catch (e) { next(e); } });
router.delete("/:id/comments/:commentId", requirePermission("comments.delete"), async (request, response, next) => { try { const filter: any = { _id: request.params.commentId, ticketId: request.params.id, deletedAt: null }; if (request.user!.role !== "SUPERADMIN") filter.authorId = request.user!.id; const comment = await Comment.findOneAndUpdate(filter, { deletedAt: new Date() }); return comment ? ok(response, null) : fail(response, 404, "COMMENT_NOT_FOUND", "Comment not found"); } catch (e) { next(e); } });
const safeUrl = z.string().url().refine((v) => /^https?:\/\//i.test(v), "Only HTTP(S) URLs are allowed");
router.post("/:id/links", requirePermission("ticket_links.create"), async (request, response, next) => { try { const input = z.object({ label: z.string().min(1).max(120), url: safeUrl }).parse(request.body); const ticket = await Ticket.findOne({ _id: request.params.id, deletedAt: null }); if (!ticket) return fail(response, 404, "TICKET_NOT_FOUND", "Ticket not found"); const link = await TicketLink.create({ ...input, ticketId: ticket._id, createdById: request.user!.id }); await activity(ticket._id, request.user!.id, "LINK_ADDED", { label: input.label }); return ok(response, link, 201); } catch (e) { next(e); } });
router.patch("/:id/links/:linkId", requirePermission("ticket_links.edit"), async (request, response, next) => { try { const input = z.object({ label: z.string().min(1).max(120).optional(), url: safeUrl.optional() }).parse(request.body); const link = await TicketLink.findOneAndUpdate({ _id: request.params.linkId, ticketId: request.params.id }, input, { new: true }); return link ? ok(response, link) : fail(response, 404, "LINK_NOT_FOUND", "Link not found"); } catch (e) { next(e); } });
router.delete("/:id/links/:linkId", requirePermission("ticket_links.delete"), async (request, response, next) => { try { const link = await TicketLink.findOneAndDelete({ _id: request.params.linkId, ticketId: request.params.id }); return link ? ok(response, null) : fail(response, 404, "LINK_NOT_FOUND", "Link not found"); } catch (e) { next(e); } });

export { router as ticketsRouter };
